### ISSUE TITLE
Song list - how to deal with song amount fatigue

### ISSUE THREAD

**Issue by Asvarox** [Asvarox/allkaraoke#188]
As of writing this, there's >1600 songs with over 200 waiting to be added. Over 1k of those are English. This makes it hard to actually pick a song.

### Favourites list
Instead of "All", the initially opened list would be "My list"/"Favourites" etc. The list would be populated through

1. ~~Players adding the songs there manually~~ (no point if singing a song adds it there)
2. Singing a song with >0 points would add it to the list
3. Custom songs would be added to the list
4. ~~If the user sung half of an artist's songs, rest would be added automatically~~ not implemented yet
5. Top 250 songs of each selected language
6. New songs (from `New` playlist - updated/added within 4 weeks)

When searching, it would look through all the songs

### Group songs by artist
~~If there are e.g. >3 songs from an artist, group them into a single entry that will expand upon selected.~~

~~Looking at what's currently added, it'd reduce the number of entries by ~600. Navigating 1k list is still hard~~

To be implemented at some point maybe

**Comment by RenBabiuch** [comment]
[2 & 3] Both, custom (unfinished) songs with > 0  points and completed songs, are not added to "My list"/"Favourites". In both cases, song is correctly marked as `Played today` in other playlists.

I think a better idea would be to add to "My list"/"Favourites" only completed songs.

**Comment by Asvarox** [comment]
2 - fixed (sung songs are being added), adding just completed songs is slightly more tricky

**Comment by Asvarox** [comment]
2 - songs that were 80% completed
3 - fixed

**Comment by Asvarox** [comment]
added indicators if a song is new or popular + a tooltip explaining what SELECTION playlist is

**Comment by RenBabiuch** [comment]
> 2 - songs that were 80% completed 3 - fixed

mm

**Comment by Asvarox** [comment]
Changes merged in #228 I'll leave this open for a while to have a place to keep any feedback in
