### ISSUE TITLE
All languages are turned on if user doesn't change anything in default selected languages

### ISSUE THREAD

**Issue by RenBabiuch** [Asvarox/allkaraoke#233]
**Description:**
In standard path, when the user before playing the game needs to select song languages - but they don't change anything in default selected ones, after clicking "continue to song selection" button, all languages are automatically turning on. In other case - when the user select/deselect any language, the settings will be saved correctly.

**Steps to reproduce:**

>1. Enter the game
>2. Choose any input type or skip it
>3. Go to sing a song (user will be automatically taken to select the language of the song first)
>4. Don't change selected song languages [in my case: English + Polish], just click "continue to song selection" button
>5. Go to playlist "Selection"/"All"
>6. Go back to main menu (by Backspace key)
>7. Go to manage songs -> select song languages

**Expected behaviour:**
The song list should contain songs in selected by user languages [English and Polish]. User's language settings should be saved correctly.

**Current behaviour:**
The song list contains songs in all selectable languages.
In second path (below), language settings are saved correctly - songs in the selected languages are visible.

>1. Enter the game
>2. Choose any input type or skip it
>3. Go to manage songs -> select song languages -> returning to main menu -> sing a song

**Comment by Asvarox** [comment]
@RenBabiuch please retest on newest master

**Comment by RenBabiuch** [comment]
> @RenBabiuch please retest on newest master

I retested it and everything works OK now, thank you :)
