### ISSUE TITLE
Songs Missing 

### ISSUE THREAD

**Issue by Gamerfronts** [Asvarox/allkaraoke#248]
What Happened to the song i was singing it just like went a way it was the new one that i added

**Comment by Gamerfronts** [comment]
it was a full list from Rihanna,drake,the black eyed peas,one direction,

**Comment by Gamerfronts** [comment]
all songs i add dont show up on your list when i share it to my friends

**Comment by Asvarox** [comment]
So the songs you share need to be validated and added by me manually to the game before they appear for everyone else. If you want to share the songs with them in the meantime (I usually go through shared songs once a week), you can download the txt file from the "edit songs" page and have them use "convert song" to paste the file contents there :) 

I'll add more clear messaging there about how sharing works

**Comment by Asvarox** [comment]
I added the disclaimer and said songs were added to the game, so I'm closing the issue :)
