### ISSUE TITLE
🔹 Improvement: after changing the tab on the remote mic - the language settings reset

### ISSUE THREAD

**Issue by RenBabiuch** [Asvarox/allkaraoke#324]
When user selects song languages on a remote mic and goes from SongList to MicMainPage (f.e. to navigate the game) or to Mic settings, when returning to Song List, the previously set lanuages are not visible as selected - instead the default languages (all) are set.

Selected languages could be visible during a user's session and not reset when they change tab - that would be helpfull for a user to don't have to set languages all the time.

https://github.com/user-attachments/assets/a9d6d6e0-9bc1-4470-a258-74d62d426162

**Comment by Asvarox** [comment]
This has been implemented
