### ISSUE TITLE
When adding a song YouTube ID should be enough

### ISSUE THREAD

**Issue by waterplea** [Asvarox/allkaraoke#79]
When I copy TXT from https://usdb.animux.de it already contains video data:

#ARTIST:Linkin Park
#TITLE:Valentine’s Day
#MP3:Linkin Park - Valentine’s Day.mp3
#CREATOR:SweetStar
#GENRE:None
#YEAR:2007
#LANGUAGE:English
#BPM:216.15
#GAP:3090
**#VIDEO:a=KAFOpywZbMM**,co=minutes-to-midnight-53a46caeae0d9.jpg,bg=linkin-park-4de523586c57e.jpg
: 0 3 9 My 
: 4 1 9 in
: 6 4 14 ~
: 12 6 12 side’s 
: 20 6 9 all 
: 28 4 7 turned 
: 36 2 9 to 
: 40 8 9 ash, 

It could be parsed from it if it's there or at least the input on the next step should also accept the ID and not only the full link.

**Comment by Asvarox** [comment]
Hi, I didn't realise it's actually there :) Thanks for the feedback and the PR, it means a ton - I'll take a look asap.

For the real BPM currently it's just used for this white-shadow-pulse thing so it matches the song tempo, but I had more ideas to utilise this info. The idea in the editor is to just click "look up" and on the google search results for most songs the number is in the exempt. But you're right, I already add metadata automatically to the songs, so I can automate this one as well, good idea :)

**Comment by waterplea** [comment]
I also added a bunch of songs and they only show up for me. I have enabled sharing the additions, do you just review them before the go public or do I need to do something else for them to become generally available?

**Comment by Asvarox** [comment]
You don't need to do anything more :) They are sent over to me (where I validate sync/volume/metadata), I have a slight backlog of these now though 😅
