### ISSUE TITLE
Feature suggestion: initial leaderboard

### ISSUE THREAD

**Issue by waterplea** [Asvarox/allkaraoke#81]
I've been working on my own karaoke browser game a few years ago. It was focused on retrowave/synthwave scene with content, as well as aesthetics. Old arcades were cool to feature some filler leaderboard values that you would try to beat. So I've made a list of famous characters from the 80s and for each song I would pre-fill the leaderboard with 10 results, varying from easy to beat to almost perfect. It could motivate people to practice and add some sense of progression.

My game also had MIDI keyboard play mode so there are 2 leaderboards there 🙂
![image](https://github.com/Asvarox/allkaraoke/assets/11832552/c4d0a947-a251-4110-a8e9-8922ebff07f6)

**Comment by Asvarox** [comment]
Thanks for the suggestion, I've implemented it couple days ago and it should be available for everyone now :)
